[Cherry-pick] Update IDSDK Client to 1.1.8 from 1.1.6 (#14790)
DynamoDS/Dynamo pull request #14797
Opened 2023-12-20 23:17 UTC by zeusongit

### Purpose

Update IDSDK Client to 1.1.8 from 1.1.6 (#14790)

### Declarations

Check these if you believe they are true

- [ ] The codebase is in a better state after this PR
- [ ] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [ ] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions) and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.
- [ ] This PR modifies some build requirements and the readme is updated
- [ ] This PR contains no files larger than 50 MB

### Release Notes

2023-12-21 02:05 UTC, pinzart90 commented on src/DynamoCore/DynamoCore.csproj
> +    <PackageReference Include="DynamoVisualProgramming.Analytics" Version="4.2.0.3421" />
Why are there 2 analytics pkgrefs? Looks like a bad merge

2023-12-21 19:07 UTC, mjkkirschner requested changes
as @pinzart90 says.

2024-01-04 20:28 UTC, QilongTang commented
@zeusongit Is this PR still targeting 3.0 hotfix?

2024-01-04 21:08 UTC, zeusongit commented
> @zeusongit Is this PR still targeting 3.0 hotfix? At least the 3.0.0 branch is now locked, should we re-target?

Yes, lets re-target, I will address the review comment

2024-01-17 19:26 UTC, closed without merging