stabilize tests and update libg
DynamoDS/Dynamo pull request #15736
Opened 2024-12-21 00:06 UTC by pinzart90

### Purpose

Update libg (more debug logs)
Stabilize tests

### Declarations

Check these if you believe they are true

- [ ] The codebase is in a better state after this PR
- [ ] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [ ] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions) and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.
- [ ] This PR modifies some build requirements and the readme is updated
- [ ] This PR contains no files larger than 50 MB

### Release Notes

(FILL ME IN) Brief description of the fix / enhancement. Use N/A to indicate that the changes in this pull request do not apply to Release Notes. **Mandatory section**

### Reviewers

(FILL ME IN) Reviewer 1 (If possible, assign the Reviewer for the PR)

(FILL ME IN, optional) Any additional notes to reviewers or testers.

### FYIs

(FILL ME IN, Optional) Names of anyone else you wish to be notified of

2025-01-02 14:54 UTC, mjkkirschner commented on test/DynamoCoreTests/Logging/AnalyticsServiceTest.cs
> +                foreach (ProcessModule module in dynamoCLI.Modules)
I think these are IDisposable.

2025-01-02 14:54 UTC, mjkkirschner commented on test/DynamoCoreTests/Logging/AnalyticsServiceTest.cs
> +                    if (module.ModuleName.IndexOf("Analytics.dll", StringComparison.OrdinalIgnoreCase) != -1)
Are all of these modules managed modules? Will this property return both managed and unmanaged?

2025-01-06 15:30 UTC, pinzart90 commented on test/Libraries/WorkflowTests/DynamoSamples.cs
> +            foreach (var process in Process.GetProcessesByName("EXCEL"))
yeah, we don't have the handle here. We do however identify the process by the title.

2025-01-06 17:17 UTC, aparajit-pratap commented on src/DynamoCoreWpf/Utilities/WebView2Utilities.cs
> +                if (Directory.Exists(newPath))
You mean if directory does not exist?

2025-01-06 18:26 UTC, aparajit-pratap commented on test/DynamoCoreWpfTests/SplashScreenTests.cs
> -            Assert.IsNull(ss.webView);// Make sure webview2 was disposed
?

2025-01-06 18:34 UTC, aparajit-pratap commented on test/Libraries/WorkflowTests/DynamoSamples.cs
> +                if (process.MainWindowTitle.Equals("ImportExport_Data To Excel - Excel"))
What process is it that does not have this title? IOW, what other titles are there? Is this title specific to Dynamo or the tests?

2025-01-14 12:19 UTC, pinzart90 commented on test/Libraries/WorkflowTests/DynamoSamples.cs
> +                if (process.MainWindowTitle.Equals("ImportExport_Data To Excel - Excel"))
The titles are specific to each dyn. If a test runs a dyn that reads/writes an excel file name "test1", then the excel window will have the title "test1 - Excel". This title is set by the excel interop API (AFAIK)

2025-01-14 19:19 UTC, pinzart90 commented on test/DynamoCoreTests/Logging/AnalyticsServiceTest.cs
> +                    if (module.ModuleName.IndexOf("Analytics.dll", StringComparison.OrdinalIgnoreCase) != -1)
both, managed and unmanaged

2025-01-14 19:20 UTC, pinzart90 commented on src/DynamoCoreWpf/Utilities/WebView2Utilities.cs
> +                if (Directory.Exists(newPath))
I removed this part. Will try it out in another PR

2025-01-15 22:52 UTC, mjkkirschner commented on src/DynamoCore/Logging/DynamoAnalyticsClient.cs
> +                lock(trackEventLockObj)
so I might be wrong - but in all other cases this lock is held from a worker thread on the thread pool, not from main thread... could this cause a dead lock?

2025-01-15 22:53 UTC, mjkkirschner commented on src/Libraries/DSOfficeUtilities/Excel.cs
> +                return GetExcelProcess(_app) != null;
could you briefly explain these changes?

2025-01-15 22:54 UTC, mjkkirschner commented on test/DynamoCoreTests/DynamoCoreTests.csproj
> -<Target Name="CopyDisableADPTestDeps">
nice

2025-01-15 22:54 UTC, mjkkirschner commented on test/DynamoCoreTests/DynamoModelTestBase.cs
> +        protected void OpenSampleModel(string relativeFilePath, bool forceManualExecution = false)
I actually think this is a binary API break for clients who derive from this class for their tests, which is public, I think you need to add a new overload.

2025-01-15 22:58 UTC, mjkkirschner commented on test/Libraries/WorkflowTests/DynamoSamples.cs
>          public void ImportExport_Excel_to_Dynamo()
does this pass now?

2025-01-15 22:59 UTC, mjkkirschner requested changes
one change request WRT to API - rest was just comments you can accept or ignore.

2025-01-16 14:46 UTC, pinzart90 commented on src/DynamoCore/Logging/DynamoAnalyticsClient.cs
> +                lock(trackEventLockObj)
From what I could tell from the [logs](https://master-5.jenkins.autodesk.com/job/Dynamo/job/DynamoSelfServe/job/pullRequestValidation/17019/testReport/junit/DynamoCoreWpfTests/CoreUserInterfaceTests/PreferenceSetting/) Looks like there is concurrent to an analytics resource (a dictionary). A dictionary is changed while it is iterated over in another thread.

2025-01-16 14:53 UTC, pinzart90 commented on src/Libraries/DSOfficeUtilities/Excel.cs
> +                return GetExcelProcess(_app) != null;
With my change we can check if the Excel process that is associated with the COM object "_app" is alive.
Previously we were checking if any process called "EXCEL" was running. It seemed that could get into situations where multiple Excel processes could get mixed up

2025-01-16 15:09 UTC, pinzart90 commented on test/Libraries/WorkflowTests/DynamoSamples.cs
>          public void ImportExport_Excel_to_Dynamo()
Fails on the master-15 machines.

2025-01-16 15:43 UTC, mjkkirschner approved these changes

2025-01-16 16:15 UTC, merged